### ISSUE TITLE
Clarification on setting up the environmet

### ISSUE THREAD

**Issue by BingPeng0** [HibaSekkat/pepper_ign_moveit2#3]
I am quite new to ROS2 and do not know why did you use docker functions in the last few steps if I have already built the workspace.
So wanted to clarify if I can straight away run or launch the example file directly in the docker environment without setting up the workspace in my local environment as I am currently using humble distribution.

**Comment by HibaSekkat** [comment]
I realized the README wasn't clear on this point, so I’ve updated it accordingly. Docker is used as an alternative for those who don't want to set up the workspace locally. It allows you to run the project in a pre-configured environment, ensuring compatibility, especially if you're using a different ROS distribution like Humble.
So yes, you can directly run the example in Docker without local setup.
